apiVersion: v1
kind: Pod
metadata:
  # This name uniquely identifies the Deployment
  name: datamon-dev
spec:
  containers:
    - name: dev
      image: golang:1.11-alpine
      tty: true
      stdin: true
      volumeMounts:
        - name: credentials
          readOnly: true
          mountPath: "/etc/datamon-creds"
        - name: riteshpv
          readOnly: true
          mountPath: "/data"
  volumes:
    - name: credentials
      secret:
        secretName: gcs-credentials
    - name: riteshpv
      persistentVolumeClaim:
        claimName: riteshpv


